### ISSUE TITLE
Unable to find chapters

### ISSUE THREAD

**Issue by StanislavMayorov** [LyndaSub/LyndaSub#14] opened 2016-01-17 08:51 UTC
exception's text: Unable to find chapters on: http://www.lynda.com/JavaScript-tutorials/Up-Running-ECMAScript-6/424003-2.html

**Comment by theshem** [comment] 2016-01-29 12:06
@Stanislav17 The issue is fixed now. #6

**Closed as completed by theshem** 2016-01-29 12:06 UTC

**Comment by StanislavMayorov** [comment] 2016-01-29 16:21
@HashemQolami thank you!
